version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-genomics
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/genomics123
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_memory_heap_initial__size=4G
      - NEO4J_dbms_memory_heap_max__size=8G
      - NEO4J_dbms_memory_pagecache_size=4G
    volumes:
      - ./neo4j_data/data:/data
      - ./neo4j_data/logs:/logs
      - ./neo4j_data/import:/var/lib/neo4j/import
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-genomics
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb-genomics
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=genomics123
      - DOCKER_INFLUXDB_INIT_ORG=genomics
      - DOCKER_INFLUXDB_INIT_BUCKET=annotations
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-genomics
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=genomics123
    volumes:
      - ./grafana_data:/var/lib/grafana
    restart: unless-stopped
