neo4j:
  container_name: "neo4j-genomics"
  neo4j_version: "5.15-community"
  data_dir: "./neo4j_data"
  memory:
    heap_initial: "4G"
    heap_max: "8G"
    pagecache: "4G"
  auth:
    user: "neo4j"
    password: "genomics123"
  ports:
    bolt: 7687
    http: 7474

download:
  download_dir: "./reference_genomes"
  max_concurrent_downloads: 3
  chunk_size: 8192
  verify_checksums: true

processing:
  segment_size: 10000
  kmer_size: 31
  batch_size: 1000
  max_workers: 8
  compression_level: 6

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/genome_db.log"
  max_file_size: "100MB"
  backup_count: 5
